### ISSUE TITLE
Mismatch between Expr and concatenation

### ISSUE THREAD

**Issue by temp** [webmozart/expression#5]
```
Expr::isEmpty()->andEmpty();
```
This should be either
```
Expr::isEmpty()->andIsEmpty();
```
or
```
Expr:empty() -> Expr::empty()->andEmpty()
```

**Comment by webmozart** [comment]
`empty` is a reserved word, hence the `is` prefix. Do you still think your suggestion should be applied?

**Comment by xabbuh** [comment]
@webmozart But you can still use reserved words as method names, can't you? So why not have an `empty()` method in the `Expr` class?

**Comment by webmozart** [comment]
@xabbuh That's true for constants (e.g. `true`, `false`, `null`), but unfortunately not for language constructs (`empty`, `instanceof`, ...). Otherwise I would have done that already. :(

**Comment by xabbuh** [comment]
@webmozart Yeah, I should have actually checked that before commenting and were too fast to answer. ;)
