### ISSUE TITLE
The contains expression should not allow type juggling when comparing equivalent expressions

### ISSUE THREAD

**Issue by stof** [webmozart/expression#7]
This can do very weird things in some cases. A strict comparison should be used instead (other expressions should be checked for similar cases btw)

**Comment by webmozart** [comment]
Could you clarify what you mean here?

**Comment by stof** [comment]
```php
$a = new Contains('foobar');

$b = new Contains(0);

var_dump($a->equivalentTo($b));
```

See https://3v4l.org/WDSPe for the evaluation (slightly simplified code to avoid defining other classes of the library not needed here)

If the ``comparedValue`` was guaranted to always be a string (scalar typehints in PHP 7 ftw), this could not happen, as the typehint would  ensure that both compared values are always from the same type (string).
But even in this case, using ``===`` would work fine (and it may trigger less operations when comparing values in PHP depending on the internal implementation of ``==`` but this is probably too micro to notice it).

Avoiding weird bugs due to type-juggling is the main reason why Symfony uses ``===`` everywhere (unless we really want the type juggling behavior).
